### ISSUE TITLE
Question about deprecation

### ISSUE THREAD

**Issue by mdlivingston** [pythops/amagpt3#1]
@pythops have you heard that they are deprecating the answers API December 3, 2022? Do you think you will build a new version of this with the completion or the embedding functions from openai? I am curious to see how you would build it.

**Comment by pythops** [comment]
Yes I read it. I'll update it next weekend I think unless someone has a PR to fix alreay

**Comment by pythops** [comment]
Updated. Thanks @mdlivingston for the reminder
