### ISSUE TITLE
Can you maximize your Q&A length limit?

### ISSUE THREAD

**Issue by dream-1ab** [pythops/amagpt3#2]
firstly thank you so much for your awesome work, unfortunately I'm living in xinjiang china (the another side of the earth) and there was a great wall for us, we cannot open google, facebook, twitter even github so we cannot use open ai services, 

our situation is hard to explain... our government is prevent us to escape their restrictions...
I can't get a open api key so I want to decide use your website for my personal research, learning purpose but that is limited to 100 character length of Q&A...

thank you again.

**Comment by pythops** [comment]
Hi, 
I understand your situation but unfortunaly I can't increase it, that would blow up the budget. I don't get any support yet for running a free instance. I pay for everything from my pocket. If one day, users start to support then of course, I will increase the limits
