### ISSUE TITLE
Make file error

### ISSUE THREAD

**Issue by fatalfeel** [pythops/amagpt3#3]
Makefile:4: recipe for target 'setup-api' failed
make: *** [setup-api] Error 1
root@homelinux:~/amagpt3#     python3 -m venv .venv && \
>     source .venv/bin/activate &&  \
>     pip3 install -U pip && \
>     pip3 install -r requirements/common.txt \
> 
Error: Command '['/root/amagpt3/.venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

**Comment by fatalfeel** [comment]
Fixed ok:
pip3 install virtualenv
gedit ~/amagpt3/Makefile
~find all
python3 -m venv .venv
~to
python3 -m virtualenv .venv

**Comment by pythops** [comment]
just make sure that you have pip installed. 
https://pip.pypa.io/en/stable/installation/

**Comment by fatalfeel** [comment]
ubuntu16  python3.7.15  
wget https://bootstrap.pypa.io/get-pip.py
python3 ./get-pip.py   #already do but still error
//
venv need change to virtualenv

**Comment by pythops** [comment]
@fatalfeel I added the ability to run amagpt3 in a container, so you don't need to deal with pip issues. Just build the image and run the container and you're ready to go
